site_url: https://djccnt15.github.io/  # necessary to enable sitemap
site_name: Note of Jay.D
site_author: djccnt15
copyright: Copyright &copy; djccnt15
# repo_url: https://github.com/djccnt15
extra_javascript:
  - javascripts/shortcuts.js
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
markdown_extensions:
  - toc:
      permalink: true
      permalink_title: Anchor link to this section for reference
  - admonition
  - abbr
  - footnotes
  - def_list
  - attr_list
  - md_in_html
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
theme:
  name: material
  custom_dir: overrides
  favicon: assets/icons/favicon.ico
  logo: assets/icons/logo_w.png
  features:
    # - navigation.instant  # turned off to solve LaTex rendering problem
    # - navigation.instant.progress  # turned off to solve LaTex rendering problem
    - navigation.tracking
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.prune
    - navigation.indexes
    - navigation.top
    # - navigation.footer
    # - navigation.expand  # not compatible with navigation.prune
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    # - header.autohide
    # - announce.dismiss
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
  palette:
    - media: "(prefers-color-scheme)"  # Palette toggle for automatic mode
      primary: blue
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"  # Palette toggle for light mode
      scheme: default
      primary: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"  # Palette toggle for dark mode
      scheme: slate
      primary: blue grey
      toggle:
        icon: material/weather-night
        name: Switch to system preference
  icon:
    repo: fontawesome/brands/github
    tag:
      api: material/api
      python: fontawesome/brands/python
      numpy: simple/numpy
      sympy: simple/sympy
      skleran: simple/scikitlearn
      pandas: simple/pandas
      java: fontawesome/brands/java
      html: fontawesome/brands/html5
      css: simple/css3
      markdown: fontawesome/brands/markdown
      git: simple/git
      terminal: simple/windowsterminal
      shell: simple/powershell
      docker: simple/docker
      redis: simple/redis
      telegram: simple/telegram
      tensorflow: simple/tensorflow
      gunicorn: simple/gunicorn
      gradle: simple/gradle
      fastapi: simple/fastapi
      django: simple/django
      spring: simple/spring
      spring_boot: simple/springboot
      jekyll: simple/jekyll
      db: fontawesome/solid/database
      mariadb: simple/mariadb
      mysql: simple/mysql
      postgresql: simple/postgresql
      mssql: simple/microsoftsqlserver
      oracle: simple/oracle
      cv: simple/opencv
      ga: simple/googleanalytics
      vscode: simple/visualstudiocode
      intellij: simple/intellijidea
extra:
  # generator: false  # enable to remove `Made with Material for MkDocs` comment at footer
  social:
    - icon: material/map-marker
      link: https://goo.gl/maps/o5VihMoDa6D26cCb7
      name: Location
    - icon: fontawesome/brands/github
      link: https://github.com/djccnt15
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/djccnt15
      name: LinkedIn
    - icon: fontawesome/regular/envelope
      link: mailto:<djccnt15@gmail.com>
      name: E-Mail
  analytics:
    provider: google
    property: G-FQG7LWZEVF
  # consent:
  #   title: Cookie consent
  #   description: >-
  #     We use cookies to recognize your repeated visits and preferences, as well
  #     as to measure the effectiveness of our documentation and whether users
  #     find what they're searching for. With your consent, you're helping us to
  #     make our documentation better.
  #   cookies:
  #     analytics: Google Analytics
  #   actions:
  #     - manage
  #     - accept
  #     - reject
  tags:
    API: api
    REST API: api
    RESTful API: api
    python: python
    PEP: python
    pip: python
    venv: python
    list comprehension: python
    numpy: numpy
    sympy: sympy
    pandas: pandas
    scikit-learn: skleran
    java: java
    java 17: java
    HTML: html
    CSS: css
    SCSS: css
    markdown: markdown
    git: git
    cmd: terminal
    terminal: terminal
    shell: powershell
    docker: docker
    redis: redis
    telegram: telegram
    tensorflow: tensorflow
    gunicorn: gunicorn
    gradle: gradle
    FastAPI: fastapi
    Django: django
    Spring: spring
    Spring batch: spring
    Jekyll: jekyll
    database: db
    RDB: db
    SQL: db
    MariaDB: mariadb
    MySQL: mysql
    PostgreSQL: postgresql
    SQL Server: mssql
    oracle: oracle
    OpenCV: cv
    Google Analytics: ga
    VS Code: vscode
    IntelliJ: intellij
plugins:
  - search:
      lang:
        - en
        - ko
  - tags:
      tags_file: pages/tags.md
  - glightbox:
      loop: true
  - blog:
      blog_toc: true
      draft_if_future_date: true
      post_date_format: medium
      post_url_format: "{categories}/{slug}"
      post_readtime: false
      post_excerpt: required
      pagination_per_page: 10
      pagination_url_format: "page/{page}"
      pagination_format: "$link_first $link_previous ~2~ $link_next $link_last"
      categories_allowed:
        - \`Draft
        - AI
        - Coding Test
        - Computer Science
        - Data Analysis
        - Data Engineering
        - Django
        - FastAPI
        - Java
        - Jekyll
        - Mathematics
        - Post
        - Python
        - Research
        - Server Engineering
        - Spring
        - Statistics
        - SW Engineering
        - Vision
        - Web
nav:
  - Home:
    - index.md
  - About:
    - About Me: pages/about/about.md
    - Career: pages/about/career.md
  - Blog:
    - blog/index.md
  - Tags:
    - pages/tags.md
  - Favorites:
    - pages/favorites.md